version: "3.3"

services:
  
  mongodb:
    image: mongo:4.4.12
    container_name: mongodb
    hostname: monogdb
    volumes:
      - ./.mongodb/data/db/:/data/db/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    restart: on-failure

  app:
    build: .
    container_name: instaclone-api
    volumes:
      - .:/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000 
    restart: on-failure
    
